version: '3'
services:
    api:
        build:
          context: ./api
        volumes:
            - ./api:/api

        command: ["python3", "demo.py", "create.live=true"]
        ports:
            - 8080:3000
